### PR TITLE
Add track-based publishing

### PR DESCRIPTION
**Pull request by knkski**
Publishes to `latest/edge` if branch name is `master` or `main`. Publishes to parsed branch name otherwise.

### CODE REVIEW

**Comment by DomFleischmann** [comment]
@jnsgruk @mmanciop I remember you two having opinions on this. What do you think of this naming approach?

**Comment by jnsgruk** [comment]
If I've grokked the bashery correctly, this is doing something slightly different to what I was proposing, which was this:

- On a PR, the CI would automatically publish to `latest/edge/pr-<pr_number>`
- On Merge, release to `latest/edge`

The first point is making use of ["branches"](https://snapcraft.io/blog/time-to-branch-out), which are hidden from the store, and ephemeral to a degree

**Comment by DomFleischmann** [comment]
> If I've grokked the bashery correctly, this is doing something slightly different to what I was proposing, which was this:
> 
>     * On a PR, the CI would automatically publish (and release) to `latest/edge/pr-<pr_number>`
> 
>     * On Merge, release to `latest/edge`
> 
> 
> The first point is making use of [branches](https://snapcraft.io/blog/time-to-branch-out), which are hidden from the store, and ephemeral to a degree, but are still deployable if you specify the full name, like `juju deploy foo --channel=latest/edge/pr-36`

I think @knkski approach still makes sense in the context of different release branches, e.g. if we have a 22.04 branch for our release and merge something to that branch we would not want to push that to `latest/edge`.

**Comment by jnsgruk** [comment]
Oh sure there is definitely scope to combine the two approaches -- the main point I was making is you can literally release every PR to a temporary branch while you're working on stuff for QA :)

**Review by DomFleischmann — APPROVED** [review]
Given that the "one track for each PR" action would be a different action to this one I think we can merge this and open another PR for the other one. 

So this LGTM.

**Pull request merged**
